spring:
  application:
    name: product-service
  profiles:
    active: local
  config:
    import: "configserver:" # config서버로부터 설정값들을 가져올 것이다. -> config 서버는 discovery 로 유레카서버로부터 가져옴
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 0 # config 서버에서 가져온 값과 구분하기 위한 더미값
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  # actuator 설정
  endpoints:
    web:
      exposure:
        include: refresh
  # zipkin 설정
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans" # zipkin 에서 정해져있는 엔드포인트임
  tracing:
    sampling:
      probability: 1.0 # 전체 모든 값을 트레이싱 (기본값 0.1)

message: "default message"